/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mystudy_ndk_JNI */

#ifndef _Included_com_example_mystudy_ndk_JNI
#define _Included_com_example_mystudy_ndk_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mystudy_ndk_JNI
 * Method:    helloFromNdk
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_example_mystudy_ndk_JNI_helloFromNdk
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
